######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 11 11:56:50 2013
######################################################################

TEMPLATE = lib
CONFIG += static release
TARGET = CurveAnalyzer
DEPENDPATH += .
INCLUDEPATH += .

MOC_DIR += .tmp
OBJECTS_DIR += .tmp
RCC_DIR += .tmp

# Input
HEADERS += curveanalyzer.h
SOURCES += curveanalyzer.cpp
