######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 25 17:29:30 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ..

# Input
HEADERS += ../legenditem.h ../colorblock.h
SOURCES += main.cpp ../legenditem.cpp ../colorblock.cpp
