######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 29 16:07:53 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ../legenditem
LIBS += -lqjson

# Input
HEADERS += mainwindow.h \
        ../curveanalyzer.h \
        ../curveplotter.h \
        ../curvelegend.h \
        ../legenditem/legenditem.h \
        ../legenditem/colorblock.h
SOURCES += main.cpp \
        mainwindow.cpp \
        ../curveanalyzer.cpp \
        ../curveplotter.cpp  \
        ../curvelegend.cpp \
        ../legenditem/legenditem.cpp \
        ../legenditem/colorblock.cpp
