######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 11 12:02:30 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../curveanalyzer.h
SOURCES += main.cpp ../curveanalyzer.cpp
