######################################################################
# Automatically generated by qmake (2.01a) Wed Jan 16 15:07:17 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../curveanalyzer.h ../curveplotter.h ../curvelegend.h
SOURCES += main.cpp ../curveanalyzer.cpp ../curveplotter.cpp ../curvelegend.cpp
